/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body #2 (LEDs+Buttons+SPI with Arduino as slave and just printing)
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <string.h> //because I want to use memset to initialize the handles to 0
#include <stdint.h>
#include <stdio.h>
#include "stm32f091rct6.h"

/*to debug with printf */
extern void initialise_monitor_handles(void);

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

enum state{OFF,ON,EMERGENCY};
enum state currentState = OFF;
uint8_t stateChanged = 0;

/*SPI communication with an Arduino (aka Ard).Whenever state changes, send it*/
//Commands
#define SPI_COMMAND_PRINT  	0x50
#define SPI_COMMAND_LED		0x51
/*Notes:in SPI comm slave will not initiate the data transfer.We send a command to Ard,Ard reads it,puts ACK/NACK.
*When the command is sent to Ard,Ard RX buffer saves this and puts an ACK/NACK in its TX.During command transmission,
*master has received garbage bytes from Ard.So before requesting ACK/NACK,we need to clear off master RX by reading.Now we can get
*Ard's ACK/NACK by sending dummy data*/
#define SPI_ARD_ACK		0xA1
#define SPI_ARD_NACK	0xB1

void delay(void)
{
	// some delay for the debouncing of the buttons
	for(uint32_t i = 0 ; i < 300000/2 ; i ++);
}

//Configurations
void peripheralConfig(void);
//Initializations
void peripheralIni(void);

int main(void)
{
	initialise_monitor_handles(); //for debugging in IDE
	printf("THIS STARTS\n");

    /*2 buttons causing interruptions: OnOff(PB3) and Emergency(PB5). 4 LEDs: PA6-9 */

	GPIO_PinHandle_t butOnOff, butEmerg, led0, led1, led2, led3;
	//initialize structures to 0 to avoid garbage values
	memset(&butOnOff,0,sizeof(butOnOff));
	memset(&butEmerg,0,sizeof(butEmerg));
	memset(&led0,0,sizeof(led0));
	memset(&led1,0,sizeof(led1));
	memset(&led2,0,sizeof(led2));
	memset(&led3,0,sizeof(led3));

	/*GPIOs for the SPI handled by spiGPIO*/
	GPIO_PinHandle_t spiGPIO;
	memset(&spiGPIO,0,sizeof(spiGPIO));

	//Configurations
	peripheralConfig(void);
	//Initializations
	peripheralIni(void);


	//configure interrupts (without priorities atm)
	//Button OnOff (GPIOB0)
	GPIO_IRQ_EnableDisable(IRQ_EXTI2_3, ENABLE);
	//Button Emergency (GPIOB2)
	GPIO_IRQ_EnableDisable(IRQ_EXTI4_15, ENABLE);

	//

	/* Loop forever */
	while (1){
		//if state changes, send print command and the content. Think about a way to do it with interrupt due to value change
		if (stateChanged) {
			//Send print command.Ard should store it in its RX buffer and put ACK in TX.Master should receive garbage in shift reg.

			//Read master RX to clear it off for the next reading

			//Send dummy data to Ard so that master receives ACK/NACK

			//Read master RX to get ACK/NACK

			//if ACK, send data (stateChanged, value state) and receive response


			//clear the flag of current state
			stateChanged = 0;
		}

	}
}

/*ISR handlers*/
void EXTI2_3_IRQHandler(void){ //when button on-off
	delay();
	GPIO_IRQ_Handling(3);
	if (currentState == OFF){
		currentState = ON;
		stateChanged = 1;
		GPIO_WritePin(GPIOA,6,0);
		GPIO_WritePin(GPIOA,7,1);
		GPIO_WritePin(GPIOA,8,1);
		GPIO_WritePin(GPIOA,9,0);
	}
	else{
		currentState = OFF;
		stateChanged = 1;
		GPIO_WritePin(GPIOA,6,0);
		GPIO_WritePin(GPIOA,7,0);
		GPIO_WritePin(GPIOA,8,0);
		GPIO_WritePin(GPIOA,9,0);
	}
	printf("%d\n",currentState);
}

void EXTI4_15_IRQHandler(void){
	delay();
	GPIO_IRQ_Handling(5);
	if (currentState != EMERGENCY){
		stateChanged = 1;
	}
	currentState = EMERGENCY;
	printf("%d\n",currentState);
	GPIO_WritePin(GPIOA,6,1);
	GPIO_WritePin(GPIOA,7,1);
	GPIO_WritePin(GPIOA,8,1);
	GPIO_WritePin(GPIOA,9,1);

}

//SPI IRQ handler for the TXE

//SPI IRQ handler for the RXNE. Is it the same as for TXE?

//Configurations
void peripheralConfig(void){

	//LEDs
	led0.pGPIO = GPIOA;
	led0.GPIO_PinConfig.GPIO_PinNumber = 6;
	led0.GPIO_PinConfig.GPIO_PinMode = GPIO_OUT;
	led0.GPIO_PinConfig.GPIO_PinOutType = GPIO_PUSHPULL;
	led0.GPIO_PinConfig.GPIO_PinOutSpeed = GPIO_SLOWSPEED; //GPIO_MEDIUMSPEED
	led0.GPIO_PinConfig.GPIO_PinPullUpDown = GPIO_NOPULL;

	led1.pGPIO = GPIOA;
	led1.GPIO_PinConfig.GPIO_PinNumber = 7;
	led1.GPIO_PinConfig.GPIO_PinMode = GPIO_OUT;
	led1.GPIO_PinConfig.GPIO_PinOutType = GPIO_PUSHPULL;
	led1.GPIO_PinConfig.GPIO_PinOutSpeed = GPIO_SLOWSPEED; //GPIO_MEDIUMSPEED
	led1.GPIO_PinConfig.GPIO_PinPullUpDown = GPIO_NOPULL;

	led2.pGPIO = GPIOA;
	led2.GPIO_PinConfig.GPIO_PinNumber = 8;
	led2.GPIO_PinConfig.GPIO_PinMode = GPIO_OUT;
	led2.GPIO_PinConfig.GPIO_PinOutType = GPIO_PUSHPULL;
	led2.GPIO_PinConfig.GPIO_PinOutSpeed = GPIO_SLOWSPEED; //GPIO_MEDIUMSPEED
	led2.GPIO_PinConfig.GPIO_PinPullUpDown = GPIO_NOPULL;

	led3.pGPIO = GPIOA;
	led3.GPIO_PinConfig.GPIO_PinNumber = 9;
	led3.GPIO_PinConfig.GPIO_PinMode = GPIO_OUT;
	led3.GPIO_PinConfig.GPIO_PinOutType = GPIO_PUSHPULL;
	led3.GPIO_PinConfig.GPIO_PinOutSpeed = GPIO_SLOWSPEED; //GPIO_MEDIUMSPEED
	led3.GPIO_PinConfig.GPIO_PinPullUpDown = GPIO_NOPULL;

	//BUTTONS
	butOnOff.pGPIO = GPIOB;
	butOnOff.GPIO_PinConfig.GPIO_PinNumber = 3;
	butOnOff.GPIO_PinConfig.GPIO_PinMode = GPIO_FALL_TRIG; //interrupt falling edge
	butOnOff.GPIO_PinConfig.GPIO_PinPullUpDown = GPIO_PULLUP; //pull up (3.3 by default)

	butEmerg.pGPIO = GPIOB;
	butEmerg.GPIO_PinConfig.GPIO_PinNumber = 5;
	butEmerg.GPIO_PinConfig.GPIO_PinMode = GPIO_FALL_TRIG;
	butEmerg.GPIO_PinConfig.GPIO_PinPullUpDown = GPIO_PULLUP;

	//GPIOs for SPI
	//CLK

	//MOSI

	//MISO

	//NSS

}
//Initializations
void peripheralIni(void){
	/*LEDs and buttons*/
	GPIO_PinInit(&led0);
	GPIO_PinInit(&led1);
	GPIO_PinInit(&led2);
	GPIO_PinInit(&led3);
	GPIO_PinInit(&butOnOff);
	GPIO_PinInit(&butEmerg);

	//LEDs OFF
	GPIO_WritePin(GPIOA,6,1);
	GPIO_WritePin(GPIOA,7,0);
	GPIO_WritePin(GPIOA,8,0);
	GPIO_WritePin(GPIOA,9,1);

	/*SPI initialization*/
	SPI_Init ;
}
